queue_rules:
  - name: test
    batch_size: 10
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {% if body | get_section("## Motivation", "") %}
      {{ body | get_section("## Motivation") }}

      {% endif %}
      {% if co_authors %}
      Co-authors: {{ co_authors | join(", ") }}
      {% endif %}
      {% if approved_reviews_by %}
      Approved by: {{ approved_reviews_by | join(", ") }}
      {% endif %}
      Merged by: @{{ merged_by }}
      {% if body | get_section("## Tickets", "") %}

      {{ body | get_section("## Tickets") }}
      {% endif %}
