queue_rules:
  - batch_size: 5
    queue_branch_merge_method: fast-forward
    queue_branch_prefix: mergify/rollup-queue/
    merge_method: merge
    allow_inplace_checks: false
    name: Rollup
    queue_conditions:
      - and:
          - label = rollup
          - linear-history = true
    merge_conditions:
      - and:
          - check-success = merge-check
    update_method: rebase
  - batch_max_wait_time: 1 s
    queue_branch_prefix: mergify/default-queue/
    merge_method: merge
    update_method: rebase
    name: Default
    allow_inplace_checks: false
    queue_conditions:
      - and:
          - label = rollup
          - linear-history = true
    merge_conditions:
      - and:
          - check-success = merge-check
