queue_rules:
  - name: test
    batch_size: 10
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {% if body | get_section("## Description") %}
      {{ body | get_section("## Description") }}

      {% endif %}
      {% if co_authors %}
      Co-authors: {% for user in co_authors %}@{{ user }}{% if not loop.last %}, {% endif %}{% endfor %}
      {% endif %}
      {% if approved_by %}
      Approved by: {% for user in approved_by %}@{{ user }}{% if not loop.last %}, {% endif %}{% endfor %}
      {% endif %}
      Merged by: @{{ merged_by }}
      {% if body | get_section("## Tickets") %}

      {{ body | get_section("## Tickets") }}
      {% endif %}
