queue_rules:
  - name: test
    batch_size: 10
    merge_method: squash
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body.split("## Motivation")[0] | trim }}
      {{ body | get_section("## Motivation") }}

      {% if co_authors %}
      Co-authors: {{ co_authors | join(", ") }}
      {% endif %}
      {% if approved_reviews_by %}
      Approved by: {{ approved_reviews_by | join(", ") }}
      {% endif %}
      Merged by: @{{ merged_by }}

      {{ body | get_section("## Tickets", "") }}
