[package]
name = "coverage-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.6" }
diesel-async = { version = "0.5.2", features = ["postgres"] }

[dev-dependencies]
tokio = { version = "1.42.0", features = ["full"] }
insta = "1.20.0"