[package]
name = "coverage-testing"
version = "0.1.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }

[dependencies]

[dev-dependencies]
insta = "1.2.0"
