name: Security audit
on:
  push:
    paths:
      - '.github/workflows/audit.yaml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'audit.toml'
  schedule:
    - cron: '0 0 * * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rust-lang/audit@v1
