name: "Test Suite"

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  debug:
    name: debug run
    runs-on: ubuntu-24.04

    steps:
      - name: debug env
        run: env

      - name: debug github run
        run: |
          echo "${{ toJson(github) }}"
          echo "${{ toJson(secrets) }}"
          echo "${{ toJson(env) }}"
