name: ci

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.7
      
      - name: Setup CC
        run: |
          bash_path=$(which bash)
          mkdir -p /tmp/.brew
          cat <<EOF > /tmp/.brew/sccache-cc-wrapper
          #!$bash_path
          exec sccache clang "$@"
          EOF
          chmod +x /tmp/.brew/sccache-cc-wrapper
          echo "/tmp/.brew" >> $GITHUB_PATH

      - name: Tap ffmpeg
        run: |
          brew tap homebrew-ffmpeg/ffmpeg

      - name: Install ffmpeg
        env:
          CC: sccache-cc-wrapper
          CXX: sccache-cc-wrapper
          HOMEBREW_CC: sccache-cc-wrapper
          HOMEBREW_CXX: sccache-cc-wrapper
        run: |
          brew install homebrew-ffmpeg/ffmpeg/ffmpeg
