name: ci

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache Homebrew Packages
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/Homebrew
            /usr/local/Cellar
            ~/Library/Caches/Homebrew
          key: homebrew-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('.github/workflows/ffmpeg-cache.yaml') }}
          restore-keys: |
            homebrew-${{ runner.os }}-${{ runner.arch }}-

      - name: Install ffmpeg
        run: |
          brew tap homebrew-ffmpeg/ffmpeg
          brew install homebrew-ffmpeg/ffmpeg/ffmpeg
