name: ci

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Tap ffmpeg
        run: |
          brew tap homebrew-ffmpeg/ffmpeg
      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: homebrew-ffmpeg/ffmpeg/ffmpeg
          cache: true
          key: macos-ffmpeg-${{ runner.os }}-${{ runner.arch }}
