name: "Test Suite"

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  debug:
    name: debug run
    runs-on: ubuntu-24.04

    steps:
      - name: hello
        run: echo "hello"

      - name: sleep
        run: sleep 30

      - name: hello
        run: echo "world"
