name: CI

on:
  pull_request:

jobs:
  fmt:
    name: fmt
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: fmt
        run: cargo fmt --all --check

  test:
    name: test
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: test
        run: cargo test --all

  lint:
    name: lint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: lint
        run: cargo clippy --all
