name: ci

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache Homebrew
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/Homebrew
            /usr/local/Cellar
            /Users/runner/Library/Caches/Homebrew/
          key: homebrew-${{ runner.os }}-${{ hashFiles('**/Brewfile') }}
          restore-keys: homebrew-${{ runner.os }}-

      - name: Install ffmpeg
        run: |
          brew install ffmpeg

