name: "Test Suite"

on:
  push:
    branches:
      - "mergify/merge-queue/*"

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        rust:
          - version: nightly
            args: "--branch"
          - version: stable
            args: ""

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        id: setup-rust
        with:
          toolchain: ${{ matrix.rust.version }}
          components: llvm-tools-preview

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
          key: "testing"

      - uses: cargo-bins/cargo-binstall@main

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest,cargo-llvm-cov,cargo-mutants,just,cargo-insta

      - run: just test-ci ${{ matrix.rust.args }}
        env:
          CARGO_TERM_COLOR: always
