name: "Test Suite"
on:
  push:
  pull_request:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: setup-rust
        toolchain: nightly
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0-rust-${{ steps.setup-rust.outputs.cachekey }}"
          key: "testing"

      - uses: cargo-bins/cargo-binstall@main

      - run: cargo binstall -y cargo-nextest cargo-llvm-cov cargo-mutants just cargo-insta

      - run: just test

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./codecov.json
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
